global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'mak3r-edge'
    scrape_interval: 5s
    static_configs:
      - targets: ['mak3r-edge:9080']
    metrics_path: '/metrics'
    scrape_timeout: 10s

  - job_name: 'edge-admin-api'
    scrape_interval: 10s
    static_configs:
      - targets: ['mak3r-edge:9080']
    metrics_path: '/netdiag/stats'
    scrape_timeout: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"